### ISSUE TITLE
Need to extend the messaging interface

### ISSUE THREAD

**Issue by k-rister** [perftool-incubator/roadblock#12]
- Want to support a more diverse collection of messages that can be shared

- Want to standardize on a "language" for the messages.  Will likely use JSON with a formalized schema which can be used to validate the integrity of the messages that each participant receives.

**Comment by k-rister** [comment]
@atheurer I believe there was a particular feature (ie. "message") that you wanted, can you document that here?  I can't recall the specifics.

**Comment by atheurer** [comment]
At the moment I can only remember one use case:  When a participant sends an abort signal, it may be useful to send an additional, more detailed message about the reason for the abort.

**Comment by atheurer** [comment]
Another possibility:  when we start running client/server benchmarks in environments where the IP used by the client is not known before the test, we will need some way to communicate this info between servers and clients.  Actually I am not even sure if the servers will know this information.  It may come from the endpoint(s).  Regardless of where it comes from, we will probably need a method for a participant to provide a message or messages to specific other participants.

**Comment by k-rister** [comment]
When you do a client/server benchmark (ie. uperf) run with rickshaw and it uses roadblock, does the client server pairs know each other's IDs that are being used for roadblock?

I'm wondering if a roadblock member broadcasts a message to all roadblock participants and says something like this is my information (in this case IP addresses) and this is my ID, would a client/server be able to know which message came from their matching client/server?

**Comment by atheurer** [comment]
> When you do a client/server benchmark (ie. uperf) run with rickshaw and it uses roadblock, does the client server pair know each other's IDs that are being used for roadblock?

Yes.  There is a env var, CS_LABEL which is [client|server]-<id>

> I'm wondering if a roadblock member broadcasts a message to all roadblock participants and says something like this is my information (in this case IP addresses) and this is my ID, would a client/server be able to know which message came from their matching client/server?

As long as all members can send a unique message and it reaches all other members, that should work.

**Comment by k-rister** [comment]
Ok, before I start working on this part we need to merge this: [https://github.com/perftool-incubator/roadblock/pull/13](https://github.com/perftool-incubator/roadblock/pull/13)

Be sure to read the last comment because you will likely need to make some small changes to rickshaw.

**Comment by atheurer** [comment]
OK, I am testing https://github.com/perftool-incubator/roadblock/pull/13 and making necessary changes to rickshaw.  I have to update a few things as I was parsing stdout to catch some of the exit status, but I think you have fixed the exit codes, should I should not need to do that anymore.

**Comment by k-rister** [comment]
Hmm, that is interesting as I don't really recall specifically doing anything with the exit codes other than making sure I kept the same behavior for abort.  What exactly do you think I fixed?

**Comment by atheurer** [comment]
At one point I think the roadblock leader would not exit with the right code if it was a time out or abort, I forget which.  I think it had to do with the parent not looking at the exit code of the forked child and exiting with that code.

**Comment by atheurer** [comment]
> When you do a client/server benchmark (ie. uperf) run with rickshaw and it uses roadblock, does the client server pair know each other's IDs that are being used for roadblock?

Yes.  There is a env var, CS_LABEL which is [client|server]-<id>

> I'm wondering if a roadblock member broadcasts a message to all roadblock participants and says something like this is my information (in this case IP addresses) and this is my ID, would a client/server be able to know which message came from their matching client/server?

As long as all members can send a unique message and it reaches all other members, that should work.
