### ISSUE TITLE
Crucible controller hits some limits when operating at scale

### ISSUE THREAD

**Issue by rajeshP524** [perftool-incubator/roadblock#60]
We are using `remotehost` endpoint in crucible for benchmarking a set of openstack VMs distributed across different provider networks. Initially we started with a small number of VMs and then started increasing the VM count which acts as servers and clients. Until 80 VMs(40 servers and 40 clients) we did not see any concerns.
And after that we tried out with 400 VMs(200 servers and 200 clients). In this we saw that the test was carried out well.. but in the post processing we did hit errors like below.
`[2024-02-09 07:06:29.184][STDOUT] sh: fork: retry: Resource temporarily unavailable
[2024-02-09 07:06:29.187][STDOUT] sh: fork: retry: Resource temporarily unavailable
`
Since crucible services are running as containers.. there are some PID limits associated with it. As a workaround to the above error.. we did increase the PID limits for the containers.

Later after that.. we have tried out with 1400 VMs(700 servers and 700 clients) to understand the crucible controller limits. We could not go forward because of the `too many open files limit error` on crucible controller.
`Deploying endpoints
endpoint-deploy-timeout adjusted to 190440 seconds
engine-script-timeout adjusted to 190440 seconds
Can't exec "/bin/sh": Too many open files at /opt/crucible/subprojects/core/rickshaw/rickshaw-run line 2170.
Can't exec "/bin/sh": Too many open files at /opt/crucible/subprojects/core/rickshaw/rickshaw-run line 2170.`
After some time... Roadblock timed out and the test failed. We have tried increasing open file limits on the crucible controller and still it seems that crucible is opening too many files or there is some limitation for the containers.

**Comment by k-rister** [comment]
Have you updated recently?  I believe that some of these issues were resolved in early-to-mid December when we did some scaling work.  We demonstrated Crucible scaling to 10,000 engines (ie. containers) across 10 remotehost endpoints.

Also, the issues that you are seeing are not related to roadblock (this repo) and should be filed against this repo: https://github.com/perftool-incubator/rickshaw

Please refile there after updating and include additional information such as as the output from `crucible repo info` and the exact command that you are executing.

**Comment by rajeshP524** [comment]
Thanks for pointing to the right place @k-rister

**Comment by rajeshP524** [comment]
Filed it here
https://github.com/perftool-incubator/rickshaw/issues/464
